services:
  postgres:
    image: postgres:latest
    container_name: greenlight-postgres
    environment:
      POSTGRES_USER: samedarslan3428
      POSTGRES_PASSWORD: Samedarslan3428
      POSTGRES_DB: greenlight
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data
    restart: always

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
    networks:
      - monitoring
    volumes:
      - ./data/grafana-data:/var/lib/grafana

networks:
  monitoring:

volumes:
  postgres_data:
  grafana-data: